@baseUrl = http://localhost:3000

# @name create_account
POST {{baseUrl}}/account
Content-Type: application/json

{
    "name": "test",
    "email": "test.com123@gmail.com",
    "password": "123456"
}

###

# @name auth
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "test.com123@gmail.com",
    "password": "123456"
}