services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: nest
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
